/* =========================================================
   Japan Trip Map — נתוני ברירת מחדל (מסלול יפן 10–26.09.2026)
   נבנה מתוך: חוברת סיכום OMERINJAPAN + מסלול שחר לוין
   התאמות: התחלה 11.09 (נחיתה 10.09 בלילה), ללא דיסני,
   האקונה לילה אחד (21–22.09).
   ========================================================= */
"use strict";

const TRIP = {
  title: "יפן–תאילנד 2026 · המפה שלנו",
  sub: "10.09–13.10+ · 🇯🇵 טוקיו → קיוטו → אוסקה → נארה → האקונה → 🇹🇭 קראבי → קופנגן → קוסמוי → בנגקוק",
  version: 1,
  klookCode: "OMERINJAPAN",
};

/* קואורדינטות — [lat, lng]. approx=true יסומן על המקום עצמו */
const COORDS = {
  "hotel-shiodome":      [35.66351, 139.75870],
  "toriyaki-ohana":      [35.66600, 139.75600],
  "meiji-shrine":        [35.67640, 139.69930],
  "takeshita-st":        [35.67160, 139.70310],
  "omotesando":          [35.66590, 139.71250],
  "onodera-omotesando":  [35.66710, 139.70860],
  "hachiko":             [35.65950, 139.70050],
  "sbux-tsutaya":        [35.65980, 139.70070],
  "katsugyu-dogenzaka":  [35.65840, 139.69640],
  "shibuya-parco":       [35.66210, 139.69870],
  "sensoji":             [35.71480, 139.79670],
  "nakamise":            [35.71270, 139.79660],
  "kappabashi":          [35.71390, 139.78870],
  "ueno-park":           [35.71460, 139.77370],
  "skytree":             [35.71010, 139.81070],
  "setsugetsuka":        [35.67170, 139.76500],
  "tokyo-station":       [35.68120, 139.76710],
  "kyoto-station":       [34.98580, 135.75850],
  "hotel-nohga":         [34.99525, 135.77415],
  "kyoto-gyoen":         [35.02540, 135.76210],
  "nijo-castle":         [35.01420, 135.74810],
  "pontocho":            [35.00930, 135.77100],
  "onodera-kyoto":       [35.00800, 135.76900],
  "monkey-park":         [35.00930, 135.67780],
  "togetsukyo":          [35.01260, 135.67760],
  "arabica-arashiyama":  [35.01350, 135.67390],
  "bamboo-grove":        [35.01700, 135.67100],
  "kijurou":             [35.01684, 135.67743],
  "kinkakuji":           [35.03940, 135.72920],
  "bungo-gion":          [35.00370, 135.77450],
  "kiyomizudera":        [34.99490, 135.78500],
  "sannenzaka":          [34.99660, 135.78100],
  "nishiki-market":      [35.00500, 135.76490],
  "maikoya":             [35.00430, 135.76250],
  "in-the-moon":         [35.00800, 135.76900],
  "fushimi-inari":       [34.96710, 135.77270],
  "fushimi-castle":      [34.93750, 135.77970],
  "gekkeikan":           [34.92960, 135.76050],
  "shijo-dori":          [35.00370, 135.76830],
  "teamlab-biovortex":   [34.98375, 135.76542],
  "marutomi":            [35.00400, 135.76800],
  "hotel-flag":          [34.67420, 135.50305],
  "kaiyukan":            [34.65450, 135.42900],
  "yodobashi-umeda":     [34.70430, 135.49610],
  "umeda-sky":           [34.70530, 135.49030],
  "dojima-yakiniku":     [34.69390, 135.49360],
  "usj":                 [34.66540, 135.43230],
  "osaka-castle":        [34.68730, 135.52620],
  "namba-yasaka":        [34.66148, 135.49673],
  "rikuros":             [34.66590, 135.50130],
  "shinsaibashi":        [34.67240, 135.50100],
  "dotonbori":           [34.66870, 135.50130],
  "nara-park":           [34.68510, 135.84300],
  "todaiji":             [34.68890, 135.83990],
  "isuien":              [34.68547, 135.83792],
  "kasuga-taisha":       [34.68140, 135.84840],
  "nakatanidou":         [34.68190, 135.82780],
  "kamaiki":             [34.68297, 135.82881],
  "osaka-station":       [34.73350, 135.50020],
  "odawara-station":     [35.25640, 139.15520],
  "hotel-suiun":         [35.23170, 139.10560],
  "openair-museum":      [35.24470, 139.05030],
  "gora-park":           [35.24820, 139.04560],
  "owakudani":           [35.24440, 139.01940],
  "togendai":            [35.24190, 138.99670],
  "hakone-shrine":       [35.20480, 139.02560],
  "roppongi-hills":      [35.66050, 139.72920],
  "midtown-2121":        [35.66670, 139.73080],
  "teamlab-borderless":  [35.66200, 139.74342],
  "tokyo-tower":         [35.65860, 139.74540],
  "savoy":               [35.65376, 139.73528],
  "ogawa-lab":           [35.66325, 139.66976],
  "reload":              [35.66310, 139.66900],
  "flippers-shimokita":  [35.66070, 139.66760],
  "shirohige":           [35.65600, 139.66890],
  "akihabara":           [35.70220, 139.77300],
  "shodai":              [35.64860, 139.70270],
  "shinjuku-gyoen":      [35.68520, 139.71000],
  "cois-cafe":           [35.69380, 139.70340],
  "uniqlo-shinjuku":     [35.69050, 139.70450],
  "godzilla":            [35.69520, 139.70190],
  "kabukicho-goldengai": [35.69420, 139.70470],
  "teamlab-planets":     [35.64930, 139.78980],
  "tsukiji":             [35.66550, 139.77070],
  "x-coffee":            [35.66900, 139.76490],
  "uniqlo-ginza":        [35.67170, 139.76360],
  "mitsukoshi-ginza":    [35.67170, 139.76450],
  "ginza-ramen":         [35.67190, 139.76590],
  "nissan-ginzasix":     [35.67050, 139.76380],
  "ginza-sand":          [35.66982, 139.76214],
  "hakkoku":             [35.67260, 139.76400],
  "airport-dep":         [35.54490, 139.76940],
  "arr-kbv":             [8.09641, 98.98512],
  "hotel-tubkaak":       [8.09143, 98.74772],
  "hotel-banyan":        [8.09663, 98.74687],
  "flight-kbv-usm":      [8.09641, 98.98512],
  "ferry-samui-phangan": [9.55600, 100.05000],
  "hotel-panviman":      [9.77646, 100.05640],
  "ferry-phangan-samui": [9.71050, 99.98850],
  "hotel-hansar":        [9.56154, 100.02578],
  "flight-usm-bkk":      [9.54883, 100.06320],
  "bkk-airport":         [13.69000, 100.75010],
};

/* קטגוריות */
const CATS = {
  site:     { he: "אתר",     icon: "⛩️" },
  food:     { he: "אוכל",    icon: "🍜" },
  shop:     { he: "קניות",   icon: "🛍️" },
  exp:      { he: "חוויה",   icon: "✨" },
  transit:  { he: "תחבורה",  icon: "🚄" },
  hotel:    { he: "לינה",    icon: "🏨" },
};

/* מקומות המסלול. שדות: n=שם עברי, en=שם באנגלית (לחיפוש/ניווט),
   city, cat, d=תיאור, part=חלק ביום, book=הערת הזמנה, site/klook=קישורים,
   approx=מיקום משוער */
const PLACES = {
  "hotel-shiodome": { n: "מלון Royal Park Iconic שיודומה", en: "The Royal Park Hotel Iconic Tokyo Shiodome", city: "טוקיו", cat: "hotel",
    d: "המלון בטוקיו — שהות ראשונה 10–13.09 ושהות שנייה 22–26.09 (הוזמן ✔, Booking.com)." },
  "toriyaki-ohana": { n: "Toriyaki Ohana — יקיטורי", en: "Toriyaki Ohana Tokyo", city: "טוקיו", cat: "food", approx: true,
    d: "יקיטורי בסגנון אומקסה — לערב הראשון, אם נשאר כוח אחרי הנחיתה.", book: "להזמין מראש דרך הקבלה / OMAKASE.IN" },
  "meiji-shrine": { n: "מקדש מייג'י", en: "Meiji Jingu Shrine", city: "טוקיו", cat: "site", part: "בוקר",
    d: "מקום שקט ומרשים בלב פארק יויוגי." },
  "takeshita-st": { n: "רחוב טאקשיטה", en: "Takeshita Street Harajuku", city: "טוקיו", cat: "shop", part: "בוקר",
    d: "רחוב הקינוחים הצבעוני של הרג'וקו; וינטג' ובתי קפה של בעלי חיים. דוכנים מומלצים בחוברת של עומר." },
  "omotesando": { n: "אומוטסנדו", en: "Omotesando Avenue", city: "טוקיו", cat: "shop", part: "צהריים",
    d: "שדרה יוקרתית, אדריכלות מודרנית ומותגי-על." },
  "onodera-omotesando": { n: "Kaiten Sushi Ginza Onodera", en: "Kaiten Sushi Ginza Onodera Omotesando", city: "טוקיו", cat: "food", part: "צהריים", approx: true,
    d: "סושי מסוע איכותי — בלי הזמנה, ממתינים בתור." },
  "hachiko": { n: "שיבויה — מעבר החצייה והאצ'יקו", en: "Shibuya Crossing Hachiko Statue", city: "טוקיו", cat: "site", part: "אחה\"צ",
    d: "מעבר החצייה המפורסם בעולם ופסל הכלב האצ'יקו." },
  "sbux-tsutaya": { n: "Starbucks Tsutaya + Share Lounge", en: "Starbucks Shibuya Tsutaya", city: "טוקיו", cat: "exp", part: "אחה\"צ",
    d: "נוף על מעבר החצייה; קומה מעל — Share Lounge (אוכל ושתייה חופשי לשעה)." },
  "katsugyu-dogenzaka": { n: "GYUKATSU Katsugyu", en: "Gyukatsu Katsugyu Dogenzaka Shibuya", city: "טוקיו", cat: "food", part: "אחה\"צ", approx: true,
    d: "שניצל וואגיו — קצר וטעים." },
  "shibuya-parco": { n: "Shibuya Parco — פוקימון ונינטנדו", en: "Shibuya PARCO", city: "טוקיו", cat: "shop", part: "ערב",
    d: "קניון עם חנות הפוקימון וחנות נינטנדו הרשמית." },
  "sensoji": { n: "מקדש סנסו-ג'י", en: "Sensoji Temple Asakusa", city: "טוקיו", cat: "site", part: "בוקר",
    d: "אסאקוסה המסורתית; המקדש הבודהיסטי העתיק בעיר. להגיע מוקדם." },
  "nakamise": { n: "שוק נקמיסה", en: "Nakamise Shopping Street", city: "טוקיו", cat: "shop", part: "בוקר",
    d: "שוק מסורתי בדרך למקדש; דוכנים מומלצים בחוברת של עומר." },
  "kappabashi": { n: "Kappabashi — רחוב כלי המטבח", en: "Kappabashi Kitchen Town", city: "טוקיו", cat: "shop", part: "צהריים",
    d: "סכינים יפניות איכותיות וכלי בית." },
  "ueno-park": { n: "פארק אואנו + גן חיות + אגם שינובאזו", en: "Ueno Park", city: "טוקיו", cat: "site", part: "אחה\"צ",
    d: "פארק גדול, גן חיות (פנדות!) ואגם שינובאזו." },
  "skytree": { n: "טוקיו סקיי-טרי", en: "Tokyo Skytree", city: "טוקיו", cat: "site", part: "ערב",
    d: "מגדל התצפית הגבוה ביפן + קניון ענק. שקיעה/לילה מומלץ.", book: "כרטיסים כמה ימים מראש (Klook)", site: "https://www.tokyo-skytree.jp/en/" },
  "setsugetsuka": { n: "Ginza Setsugetsuka — וואגיו אומקסה", en: "Ginza Setsugetsuka", city: "טוקיו", cat: "food", part: "ערב", approx: true,
    d: "וואגיו אומקסה ברמה גבוהה.", book: "להזמין מראש דרך הקבלה / OMAKASE.IN" },
  "tokyo-station": { n: "שינקנסן טוקיו ← קיוטו", en: "Tokyo Station", city: "טוקיו", cat: "transit",
    d: "כ-2:15 בנוזומי/היקארי. עם מזוודות גדולות — להזמין מושבים 1-2 שבועות מראש.", book: "כרטיס מראש — Klook (קוד OMERINJAPAN)" },
  "kyoto-station": { n: "תחנת קיוטו — הגעה", en: "Kyoto Station", city: "קיוטו", cat: "transit",
    d: "מהתחנה למלון: מונית קצרה או אוטובוס. אפשר לשלוח מזוודות מהמלון הקודם." },
  "hotel-nohga": { n: "מלון Nohga קיומיזו", en: "Nohga Hotel Kiyomizu Kyoto", city: "קיוטו", cat: "hotel",
    d: "המלון בקיוטו 13–17.09 (הוזמן ✔, Booking.com)." },
  "kyoto-gyoen": { n: "גני הארמון — Kyoto Gyoen", en: "Kyoto Gyoen National Garden", city: "קיוטו", cat: "site", part: "צהריים",
    d: "פארק ענק עם גנים יפניים סביב ארמון הקיסר." },
  "nijo-castle": { n: "טירת ניג'ו", en: "Nijo Castle", city: "קיוטו", cat: "site", part: "אחה\"צ",
    d: "טירת השוגון — רצפות \"הזמיר\" המפורסמות." },
  "pontocho": { n: "פונטוצ'ו", en: "Pontocho Alley", city: "קיוטו", cat: "exp", part: "ערב",
    d: "סמטה ציורית לאורך הנהר עם ברים ומסעדות." },
  "onodera-kyoto": { n: "Kaiten Sushi Onodera קיוטו", en: "Kaiten Sushi Ginza Onodera Kyoto", city: "קיוטו", cat: "food", part: "ערב", approx: true,
    d: "סושי מסוע ברמה גבוהה." },
  "monkey-park": { n: "פארק הקופים איוואטאיאמה", en: "Iwatayama Monkey Park Arashiyama", city: "קיוטו", cat: "site", part: "בוקר",
    d: "עלייה קצרה, קופי מקוק חופשיים ונוף על קיוטו. כרטיסים במקום." },
  "togetsukyo": { n: "גשר טוגטסוקיו", en: "Togetsukyo Bridge", city: "קיוטו", cat: "site", part: "בוקר",
    d: "הגשר הסמל של אראשיאמה." },
  "arabica-arashiyama": { n: "% Arabica אראשיאמה", en: "% Arabica Kyoto Arashiyama", city: "קיוטו", cat: "food", part: "בוקר",
    d: "קפה מעולה עם נוף לנהר." },
  "bamboo-grove": { n: "יער הבמבוק", en: "Arashiyama Bamboo Grove", city: "קיוטו", cat: "site", part: "בוקר",
    d: "שביל הבמבוק המפורסם — כמה שיותר מוקדם, פחות עמוס." },
  "kijurou": { n: "Kijurou — וואגיו", en: "Kijurou Arashiyama", city: "קיוטו", cat: "food", part: "צהריים",
    d: "מסעדת וואגיו ~10 דקות מיער הבמבוק." },
  "kinkakuji": { n: "מקדש הזהב — קינקאקו-ג'י", en: "Kinkakuji Golden Pavilion", city: "קיוטו", cat: "site", part: "אחה\"צ",
    d: "הביתן המוזהב על האגם — מהמקדשים המרשימים ביפן." },
  "bungo-gion": { n: "Wagyu Ryotei Bungo — גיון", en: "Wagyu Ryotei Bungo Gion", city: "קיוטו", cat: "food", part: "ערב", approx: true,
    d: "ארוחת וואגיו אומקסה מעולה.", book: "להזמין מראש דרך הקבלה" },
  "kiyomizudera": { n: "קיומיזו-דרה", en: "Kiyomizu-dera Temple", city: "קיוטו", cat: "site", part: "בוקר",
    d: "מקדש על במת עץ עם תצפית על העיר. להגיע מוקדם!" },
  "sannenzaka": { n: "סאננזאקה + השכרת קימונו", en: "Sannenzaka Ninenzaka", city: "קיוטו", cat: "site", part: "בוקר",
    d: "סמטאות ציוריות; Starbucks מיוחד בבית מסורתי; קימונו ב-Yume Kyoto Kodaiji." },
  "nishiki-market": { n: "שוק נישיקי", en: "Nishiki Market Kyoto", city: "קיוטו", cat: "food", part: "צהריים",
    d: "\"המטבח של קיוטו\". ראמן KYOTO ENGINE (אופ' צמחונית), KOE DONUTS. דוכנים בחוברת." },
  "maikoya": { n: "טקס תה MAIKOYA", en: "MAIKOYA Kyoto Nishiki Tea Ceremony", city: "קיוטו", cat: "exp", part: "אחה\"צ", approx: true,
    d: "טקס תה מסורתי ליד שוק נישיקי.", book: "להזמין כשבוע מראש", site: "https://mai-ko.com/" },
  "in-the-moon": { n: "בר רופטופ in the moon", en: "in the moon rooftop bar Kyoto", city: "קיוטו", cat: "exp", part: "ערב", approx: true,
    d: "בר על גג עם נוף לעיר." },
  "fushimi-inari": { n: "פושימי אינארי", en: "Fushimi Inari Taisha", city: "קיוטו", cat: "site", part: "בוקר",
    d: "אלפי שערי טורי כתומים במעלה ההר. מוקדם = ריק יותר." },
  "fushimi-castle": { n: "טירת פושימי", en: "Fushimi Momoyama Castle", city: "קיוטו", cat: "site", part: "צהריים",
    d: "טירה משוחזרת בפארק שקט (מבחוץ)." },
  "gekkeikan": { n: "מחוז הסאקה — Gekkeikan Okura", en: "Gekkeikan Okura Sake Museum Fushimi", city: "קיוטו", cat: "exp", part: "צהריים",
    d: "מבשלות סאקה היסטוריות + מוזיאון וטעימות (אם יש זמן)." },
  "shijo-dori": { n: "שדרת שיג'ו", en: "Shijo Dori Kyoto", city: "קיוטו", cat: "shop", part: "אחה\"צ",
    d: "רחוב הקניות המרכזי של קיוטו." },
  "teamlab-biovortex": { n: "teamLab Biovortex קיוטו", en: "teamLab Biovortex Kyoto", city: "קיוטו", cat: "exp", part: "אחה\"צ",
    d: "סופר מומלץ! עדיף אחר הצהריים.", book: "להזמין שבוע-שבועיים מראש", site: "https://www.teamlab.art/" },
  "marutomi": { n: "Yakiniku MARUTOMI", en: "Yakiniku Marutomi Kyoto", city: "קיוטו", cat: "food", part: "ערב", approx: true,
    d: "יאקיניקו מעולה במחיר טוב." },
  "hotel-flag": { n: "HOTEL THE FLAG שינסאיבאשי", en: "Hotel The Flag Shinsaibashi Osaka", city: "אוסקה", cat: "hotel",
    d: "המלון באוסקה 17–21.09 (הוזמן ✔, Booking.com)." },
  "kaiyukan": { n: "אקווריום קאיוקאן", en: "Osaka Aquarium Kaiyukan", city: "אוסקה", cat: "site", part: "צהריים",
    d: "מהאקווריומים הגדולים והמרשימים באסיה — לווייתני-נמר ענקיים.", site: "https://www.kaiyukan.com/language/eng/", klook: "https://shorturl.at/6mC7v" },
  "yodobashi-umeda": { n: "Yodobashi Camera אומדה", en: "Yodobashi Umeda", city: "אוסקה", cat: "shop", part: "אחה\"צ",
    d: "מרכז אלקטרוניקה/קניות ענק ליד התחנה." },
  "umeda-sky": { n: "Umeda Sky Building", en: "Umeda Sky Building", city: "אוסקה", cat: "site", part: "ערב",
    d: "תצפית פנורמית מקומה 39 — מדהים בשקיעה.", klook: "https://shorturl.at/2sUUm" },
  "dojima-yakiniku": { n: "Dojima Yakiniku — אומקסה", en: "Dojima Yakiniku Osaka", city: "אוסקה", cat: "food", part: "ערב", approx: true,
    d: "וואגיו אומקסה ברמה גבוהה.", book: "להזמין מראש דרך הקבלה" },
  "usj": { n: "יוניברסל סטודיוס יפן", en: "Universal Studios Japan", city: "אוסקה", cat: "exp", part: "כל היום",
    d: "להגיע שעה לפני הפתיחה! נינטנדו-וורלד והארי פוטר. אפליקציה עם זמני המתנה.",
    book: "כרטיסים + אקספרס פס חודש מראש", site: "https://www.usj.co.jp/web/en/us", klook: "https://shorturl.at/hlyTU" },
  "osaka-castle": { n: "טירת אוסקה", en: "Osaka Castle", city: "אוסקה", cat: "site", part: "בוקר",
    d: "הטירה ההיסטורית והגנים.", klook: "https://shorturl.at/6f2f7" },
  "namba-yasaka": { n: "מקדש נמבה יאסאקה", en: "Namba Yasaka Shrine", city: "אוסקה", cat: "site", part: "צהריים",
    d: "הבמה בצורת ראש אריה ענק — פוטוגני במיוחד." },
  "rikuros": { n: "עוגת גבינה Rikuro's", en: "Rikuro Ojisan Namba Main Branch", city: "אוסקה", cat: "food", part: "צהריים", approx: true,
    d: "עוגת הגבינה היפנית הרוטטת — חם מהתנור." },
  "shinsaibashi": { n: "שינסאיבאשי + Pablo", en: "Shinsaibashi Suji Shopping Street", city: "אוסקה", cat: "shop", part: "אחה\"צ",
    d: "מדרחוב הקניות הגדול; טארט גבינה של Pablo." },
  "dotonbori": { n: "דוטונבורי", en: "Dotonbori Osaka", city: "אוסקה", cat: "exp", part: "ערב",
    d: "שלטי הניאון, שלט הגלידו-מן, שייט על התעלה, אוכל רחוב ו-Don Quijote הענקית." },
  "nara-park": { n: "פארק האיילים נארה", en: "Nara Park", city: "נארה", cat: "site", part: "בוקר",
    d: "האכלת איילים משתחווים (קרקרים במקום)." },
  "todaiji": { n: "מקדש טודאי-ג'י", en: "Todaiji Temple Nara", city: "נארה", cat: "site", part: "בוקר",
    d: "בודהה הענק בהיכל העץ הגדול בעולם." },
  "isuien": { n: "גן איסוי-אן", en: "Isuien Garden Nara", city: "נארה", cat: "site", part: "בוקר",
    d: "גן יפני קלאסי ושקט." },
  "kasuga-taisha": { n: "מקדש קסוגה טאישה", en: "Kasuga Taisha Nara", city: "נארה", cat: "site", part: "צהריים",
    d: "מקדש הפנסים בלב היער." },
  "nakatanidou": { n: "מוצ'י Nakatanidou", en: "Nakatanidou Mochi Nara", city: "נארה", cat: "food", part: "צהריים",
    d: "הכנת המוצ'י המהירה והמפורסמת — מופע בפני עצמו." },
  "kamaiki": { n: "אודון Kamaiki (מישלן)", en: "Udon Kamaiki Nara", city: "נארה", cat: "food", part: "צהריים",
    d: "אודון מומלץ מישלן, 3 דקות מחנות המוצ'י." },
  "osaka-station": { n: "רכבת אוסקה ← אודווארה (האקונה)", en: "Shin-Osaka Station", city: "אוסקה", cat: "transit",
    d: "שינקנסן משין-אוסקה לאודווארה (~3 שעות), משם אוטובוס/רכבת גורה להאקונה.", book: "כרטיס מראש — Klook (קוד OMERINJAPAN)" },
  "odawara-station": { n: "תחנת אודווארה — מעבר להאקונה", en: "Odawara Station", city: "האקונה", cat: "transit",
    d: "מכאן רכבת האקונה-טוזאן / אוטובוס אל אזור גורה. שליחת מזוודות מראש מומלצת." },
  "hotel-suiun": { n: "ריוקאן Suiun — לילה באונסן", en: "Hakone Suiun Ryokan", city: "האקונה", cat: "hotel", approx: true,
    d: "לילה אחד 21–22.09 (הוזמן ✔). ערב אונסן — להגיע לארוחת הערב בזמן!" },
  "openair-museum": { n: "המוזיאון הפתוח של האקונה", en: "Hakone Open-Air Museum", city: "האקונה", cat: "site", part: "אחה\"צ",
    d: "פסלים ואמנות בטבע, אולם פיקאסו ומגדל הוויטראז'ים." },
  "gora-park": { n: "גני גורה", en: "Hakone Gora Park", city: "האקונה", cat: "site", part: "אחה\"צ",
    d: "גן צרפתי מטופח על ההר." },
  "owakudani": { n: "עמק הגעש אוואקודאני", en: "Owakudani", city: "האקונה", cat: "site", part: "בוקר",
    d: "רכבל מעל עמק גופרית פעיל; ביצים שחורות; ביום בהיר — הר פוג'י." },
  "togendai": { n: "שייט אגם אשי — ספינת פיראטים", en: "Hakone Sightseeing Cruise Togendai", city: "האקונה", cat: "exp", part: "צהריים",
    d: "מפליגים מטוגנדאי למוטו-האקונה על פני האגם.", site: "https://www.hakonenavi.jp/international/en/" },
  "hakone-shrine": { n: "מקדש האקונה — הטורי הצף", en: "Hakone Shrine", city: "האקונה", cat: "site", part: "אחה\"צ",
    d: "שער הטורי האדום במים — תור קצר לתמונה, שווה." },
  "roppongi-hills": { n: "רופונגי הילס + טוקיו מידטאון", en: "Roppongi Hills", city: "טוקיו", cat: "shop", part: "בוקר",
    d: "מתחמי קניות ואדריכלות; תצפית מוזיאון מורי (אופציה)." },
  "midtown-2121": { n: "21_21 Design Sight", en: "21_21 Design Sight Tokyo", city: "טוקיו", cat: "site", part: "צהריים",
    d: "מוזיאון עיצוב של טדאו אנדו בגני מידטאון." },
  "teamlab-borderless": { n: "teamLab Borderless", en: "teamLab Borderless Azabudai Hills", city: "טוקיו", cat: "exp", part: "אחה\"צ",
    d: "מוזיאון האמנות הדיגיטלית באזאבודאי הילס.", book: "להזמין שבוע-שבועיים מראש", klook: "https://shorturl.at/Zxcee" },
  "tokyo-tower": { n: "מגדל טוקיו", en: "Tokyo Tower", city: "טוקיו", cat: "site", part: "ערב",
    d: "המגדל האדום האיקוני — יפה במיוחד מואר בלילה.", klook: "https://shorturl.at/kLzxS" },
  "savoy": { n: "פיצה Savoy", en: "Savoy Azabujuban Pizza", city: "טוקיו", cat: "food", part: "ערב",
    d: "מהפיצות הטובות בטוקיו — נאפוליטנה קטנה ואינטימית.", book: "להזמין מראש דרך הקבלה" },
  "ogawa-lab": { n: "Ogawa Coffee Lab", en: "Ogawa Coffee Laboratory Shimokitazawa", city: "טוקיו", cat: "food", part: "בוקר",
    d: "מעבדת קפה — פתיחת בוקר בשימוקיטזאווה." },
  "reload": { n: "מתחם reload", en: "reload Shimokitazawa", city: "טוקיו", cat: "shop", part: "בוקר",
    d: "מתחם חנויות עיצוב, יד-שנייה ואופנה." },
  "flippers-shimokita": { n: "פנקייק Flipper's", en: "Flippers Shimokitazawa", city: "טוקיו", cat: "food", part: "בוקר", approx: true,
    d: "פנקייק סופלה פלאפי." },
  "shirohige": { n: "Shiro-Hige's — שו קרם טוטורו", en: "Shiro-Hige Cream Puff Factory", city: "טוקיו", cat: "food", part: "צהריים", approx: true,
    d: "בית קפה בהשראת ג'יבלי — שו קרם בצורת טוטורו." },
  "shinjuku-gyoen": { n: "גן שינג'וקו גיואן", en: "Shinjuku Gyoen National Garden", city: "טוקיו", cat: "site", part: "אחה\"צ",
    d: "גן המשלב סגנון יפני, צרפתי ואנגלי (נסגר ~17:30-18:00)." },
  "cois-cafe": { n: "cois cafe — קרם ברולה", en: "cois cafe Shinjuku", city: "טוקיו", cat: "food", part: "אחה\"צ", approx: true,
    d: "בית הקפה של הקרם-ברולה." },
  "uniqlo-shinjuku": { n: "UNIQLO שינג'וקו (דגל)", en: "UNIQLO Shinjuku Flagship", city: "טוקיו", cat: "shop", part: "אחה\"צ", approx: true,
    d: "חנות הדגל בשינג'וקו." },
  "godzilla": { n: "ראש הגודזילה", en: "Godzilla Head Hotel Gracery Shinjuku", city: "טוקיו", cat: "site", part: "ערב",
    d: "גודזילה מציץ מגג מלון Gracery בקאבוקיצ'ו." },
  "kabukicho-goldengai": { n: "קאבוקיצ'ו + גולדן גאי", en: "Golden Gai Shinjuku", city: "טוקיו", cat: "exp", part: "ערב",
    d: "אזור הניאון התוסס וסמטאות הברים הזעירים של גולדן גאי." },
  "teamlab-planets": { n: "teamLab Planets", en: "teamLab Planets Toyosu", city: "טוקיו", cat: "exp", part: "אחה\"צ",
    d: "חוויית האמנות במים — יחפים בתוך המיצבים. ליד טויוסו/גינזה.", book: "להזמין דרך Klook", klook: "https://shorturl.at/gcmU9" },
  "tsukiji": { n: "שוק צוקיג'י", en: "Tsukiji Outer Market", city: "טוקיו", cat: "food", part: "בוקר",
    d: "שוק הדגים החיצוני — טעימות בוקר: טמאגו, סשימי, אוני. לבוא רעבים." },
  "x-coffee": { n: "X coffee גינזה", en: "X coffee Ginza", city: "טוקיו", cat: "food", part: "בוקר", approx: true,
    d: "מעבדת קפה מגניבה." },
  "uniqlo-ginza": { n: "UNIQLO גינזה", en: "UNIQLO Ginza", city: "טוקיו", cat: "shop", part: "צהריים",
    d: "חנות היוניקלו הגדולה בעולם — 12 קומות." },
  "mitsukoshi-ginza": { n: "מיצוקושי גינזה — דפאצ'יקה", en: "Ginza Mitsukoshi", city: "טוקיו", cat: "shop", part: "צהריים",
    d: "קומות המרתף/2-3: שוק אוכל יוקרתי וקינוחים מטריפים." },
  "ginza-ramen": { n: "ראמן מישלן: Kagari / Hachigou", en: "Ginza Kagari Ramen", city: "טוקיו", cat: "food", part: "צהריים", approx: true,
    d: "Kagari — תור (ציר עוף קרמי); Hachigou — בהזמנה.", book: "Hachigou: TableCheck / Tabelog" },
  "nissan-ginzasix": { n: "בניין ניסאן + Ginza Six", en: "Ginza Six", city: "טוקיו", cat: "shop", part: "אחה\"צ",
    d: "תצוגת הרכבים של ניסאן ומרכז הקניות היוקרתי Ginza Six." },
  "ginza-sand": { n: "ginza sand — סנדוויץ' וואגיו", en: "Ginza Sand Tokyo", city: "טוקיו", cat: "food", part: "אחה\"צ",
    d: "כריך קצוצת וואגיו וסלט ביצים." },
  "hakkoku": { n: "סושי Hakkoku", en: "Hakkoku Ginza Sushi", city: "טוקיו", cat: "food", part: "ערב", approx: true,
    d: "סושי אומקסה ברמה גבוהה — ארוחת הסיום.", book: "להזמין מראש — OMAKASE.IN" },
  "akihabara": { n: "אקיהברה (אופציונלי)", en: "Akihabara Electric Town", city: "טוקיו", cat: "shop", part: "לילה",
    d: "אנימה, אלקטרוניקה וארקיידים (פתוחים עד ~23:00); Don Quijote 24/7. אפשר גם לשבץ ביום 13." },
  "airport-dep": { n: "טיסה לתאילנד ✈️", en: "Haneda Airport", city: "טוקיו", cat: "transit", approx: true,
    d: "26.09 — טיסה טוקיו ← קראבי. לוודא בכרטיס: הנדה או נריטה, ולתזמן יציאה בהתאם." },
};

/* הימים. stops = מזהי מקומות לפי סדר הביקור */
const DAYS = [
  { id: "d0", n: 0, date: "10.09", dow: "חמישי", city: "טוקיו", color: "#64748b",
    title: "נחיתה בטוקיו",
    sum: "נחיתה בלילה, צ'ק-אין בשיודומה. אם נשאר כוח — יקיטורי ליד המלון.",
    hotel: "hotel-shiodome",
    transit: "משדה התעופה: נריטה — Narita Express / לימוזין-באס; הנדה — מונית סבירה או רכבת.",
    stops: ["hotel-shiodome", "toriyaki-ohana"] },
  { id: "d1", n: 1, date: "11.09", dow: "שישי", city: "טוקיו", color: "#e11d48",
    title: "הרג'וקו ושיבויה",
    sum: "מקדש מייג'י, טאקשיטה ואומוטסנדו, ואחה\"צ שיבויה — האצ'יקו, סטארבקס והפארקו.",
    hotel: "hotel-shiodome",
    stops: ["meiji-shrine", "takeshita-st", "omotesando", "onodera-omotesando", "hachiko", "sbux-tsutaya", "katsugyu-dogenzaka", "shibuya-parco"] },
  { id: "d2", n: 2, date: "12.09", dow: "שבת", city: "טוקיו", color: "#ea580c",
    title: "אסאקוסה, אואנו וסקיי-טרי",
    sum: "טוקיו המסורתית: סנסו-ג'י ונקמיסה, כלי מטבח בקפבאשי, פארק אואנו, וערב בסקיי-טרי.",
    hotel: "hotel-shiodome",
    stops: ["sensoji", "nakamise", "kappabashi", "ueno-park", "skytree", "setsugetsuka"] },
  { id: "d3", n: 3, date: "13.09", dow: "ראשון", city: "קיוטו", color: "#ca8a04",
    title: "שינקנסן לקיוטו",
    sum: "בוקר שינקנסן, צ'ק-אין, גני הארמון וטירת ניג'ו, וערב ראשון בפונטוצ'ו.",
    hotel: "hotel-nohga",
    transit: "שינקנסן טוקיו←קיוטו ~2:15. להזמין מראש (Klook, קוד OMERINJAPAN).",
    stops: ["tokyo-station", "kyoto-station", "hotel-nohga", "kyoto-gyoen", "nijo-castle", "pontocho", "onodera-kyoto"] },
  { id: "d4", n: 4, date: "14.09", dow: "שני", city: "קיוטו", color: "#65a30d",
    title: "אראשיאמה ומקדש הזהב",
    sum: "בוקר בין הקופים, הגשר ויער הבמבוק; צהריים וואגיו; אחה\"צ קינקאקו-ג'י; ערב גיון.",
    hotel: "hotel-nohga",
    stops: ["monkey-park", "togetsukyo", "arabica-arashiyama", "bamboo-grove", "kijurou", "kinkakuji", "bungo-gion"] },
  { id: "d5", n: 5, date: "15.09", dow: "שלישי", city: "קיוטו", color: "#059669",
    title: "קיומיזו, נישיקי וטקס תה",
    sum: "השכם לקיומיזו-דרה וסאננזאקה (קימונו!), שוק נישיקי, טקס תה, וערב ברופטופ.",
    hotel: "hotel-nohga",
    stops: ["kiyomizudera", "sannenzaka", "nishiki-market", "maikoya", "in-the-moon"] },
  { id: "d6", n: 6, date: "16.09", dow: "רביעי", city: "קיוטו", color: "#0d9488",
    title: "פושימי אינארי וטים-לאב",
    sum: "שערי הטורי של פושימי, מחוז הסאקה, שיג'ו-דורי, ו-teamLab Biovortex אחה\"צ.",
    hotel: "hotel-nohga",
    stops: ["fushimi-inari", "fushimi-castle", "gekkeikan", "shijo-dori", "teamlab-biovortex", "marutomi"] },
  { id: "d7", n: 7, date: "17.09", dow: "חמישי", city: "אוסקה", color: "#0891b2",
    title: "מעבר לאוסקה",
    sum: "רכבת קצרה לאוסקה, אקווריום קאיוקאן, אלקטרוניקה באומדה ושקיעה מ-Umeda Sky.",
    hotel: "hotel-flag",
    transit: "קיוטו←אוסקה: JR מהיר ~30 דק' לתחנת אוסקה (או שינקנסן לשין-אוסקה ~15 דק').",
    stops: ["hotel-flag", "kaiyukan", "yodobashi-umeda", "umeda-sky", "dojima-yakiniku"] },
  { id: "d8", n: 8, date: "18.09", dow: "שישי", city: "אוסקה", color: "#2563eb",
    title: "יוניברסל סטודיוס",
    sum: "יום שלם בפארק — להגיע שעה לפני הפתיחה. נינטנדו-וורלד דורש תזמון!",
    hotel: "hotel-flag",
    stops: ["usj"] },
  { id: "d9", n: 9, date: "19.09", dow: "שבת", city: "אוסקה", color: "#4f46e5",
    title: "טירת אוסקה ודוטונבורי",
    sum: "טירה בבוקר, נמבה ועוגת גבינה, שינסאיבאשי, וערב ניאונים ושייט בדוטונבורי.",
    hotel: "hotel-flag",
    stops: ["osaka-castle", "namba-yasaka", "rikuros", "shinsaibashi", "dotonbori"] },
  { id: "d10", n: 10, date: "20.09", dow: "ראשון", city: "נארה", color: "#7c3aed",
    title: "יום איילים בנארה",
    sum: "פארק האיילים, טודאי-ג'י, גן איסוי-אן, קסוגה טאישה, מוצ'י ואודון מישלן. חזרה לאוסקה.",
    hotel: "hotel-flag",
    transit: "אוסקה←נארה: רכבת קינטצו מנמבה ~35-40 דק'.",
    stops: ["nara-park", "todaiji", "isuien", "kasuga-taisha", "nakatanidou", "kamaiki"] },
  { id: "d11", n: 11, date: "21.09", dow: "שני", city: "האקונה", color: "#9333ea",
    title: "להאקונה — אמנות ואונסן",
    sum: "בוקר נסיעה, אחה\"צ המוזיאון הפתוח וגני גורה, וערב ריוקאן עם אונסן.",
    hotel: "hotel-suiun",
    transit: "שינקנסן שין-אוסקה←אודווארה ~3 שעות + רכבת/אוטובוס לגורה. לשלוח מזוודות לטוקיו מראש!",
    stops: ["osaka-station", "odawara-station", "openair-museum", "gora-park", "hotel-suiun"] },
  { id: "d12", n: 12, date: "22.09", dow: "שלישי", city: "האקונה ← טוקיו", color: "#c026d3",
    title: "לולאת האקונה וחזרה לטוקיו",
    sum: "רכבל לאוואקודאני (פוג'י!), שייט פיראטים באגם אשי, הטורי הצף — ובערב חזרה לטוקיו.",
    hotel: "hotel-shiodome",
    transit: "בערב: אודווארה←טוקיו שינקנסן ~35 דק'. ערב חופשי בשיודומה.",
    stops: ["owakudani", "togendai", "hakone-shrine", "odawara-station", "hotel-shiodome"] },
  { id: "d13", n: 13, date: "23.09", dow: "רביעי", city: "טוקיו", color: "#db2777",
    title: "רופונגי, טים-לאב ומגדל טוקיו",
    sum: "עיצוב ואמנות: רופונגי הילס ו-21_21, teamLab Borderless, מגדל טוקיו בלילה ופיצה ב-Savoy.",
    hotel: "hotel-shiodome",
    stops: ["roppongi-hills", "midtown-2121", "teamlab-borderless", "tokyo-tower", "savoy"] },
  { id: "d14", n: 14, date: "24.09", dow: "חמישי", city: "טוקיו", color: "#dc2626",
    title: "שימוקיטזאווה ושינג'וקו",
    sum: "בוקר היפסטרי בשימוקיטה (קפה, reload, פנקייק, טוטורו), אחה\"צ שינג'וקו וערב גולדן גאי.",
    hotel: "hotel-shiodome",
    stops: ["ogawa-lab", "reload", "flippers-shimokita", "shirohige", "shinjuku-gyoen", "cois-cafe", "uniqlo-shinjuku", "godzilla", "kabukicho-goldengai", "shodai"] },
  { id: "d15", n: 15, date: "25.09", dow: "שישי", city: "טוקיו", color: "#92400e",
    title: "צוקיג'י, גינזה וסיום ב-teamLab Planets",
    sum: "בוקר טעימות בצוקיג'י, יום גינזה (ראמן מישלן!), teamLab Planets, וארוחת סיום ב-Hakkoku.",
    hotel: "hotel-shiodome",
    stops: ["tsukiji", "x-coffee", "uniqlo-ginza", "mitsukoshi-ginza", "ginza-ramen", "nissan-ginzasix", "ginza-sand", "teamlab-planets", "hakkoku", "akihabara"] },
  { id: "d16", n: 16, date: "26.09", dow: "שבת", city: "טוקיו", color: "#475569",
    title: "טיסה לתאילנד",
    sum: "צ'ק-אאוט וטיסה טוקיו ← קראבי. להגיע לשדה 3 שעות לפני.",
    hotel: null,
    stops: ["airport-dep"] },
];

/* shodai חסר ב-PLACES? נוסיף */
PLACES["shodai"] = { n: "shodai — אודון קארי", en: "Curry Udon Shodai Tokyo", city: "טוקיו", cat: "food", part: "ערב", approx: true,
  d: "אודון קארי עם קציפת תפוחי אדמה (חלבי+בשרי).", };

/* ---------- תאילנד 🇹🇭 (26.09–13.10+) ---------- */
Object.assign(PLACES, {
  "arr-kbv": { n: "נחיתה בקראבי ✈️", en: "Krabi International Airport", city: "קראבי", cat: "transit",
    d: "26.09 · טיסה מטוקיו (קבלה 1357764, bookaflight) — לוודא שעה בכרטיס. משדה התעופה ~40 דק' נסיעה למלון." },
  "hotel-tubkaak": { n: "The Tubkaak Krabi Boutique Resort", en: "The Tubkaak Krabi Boutique Resort", city: "קראבי", cat: "hotel",
    d: "26–28.09 · הוזמן ✔ (Agoda 672013915) · כולל ארוחת בוקר · חוף טובקק השקט, מול איי הונג." },
  "hotel-banyan": { n: "Banyan Tree Krabi", en: "Banyan Tree Krabi", city: "קראבי", cat: "hotel",
    d: "28.09–01.10 · הוזמן ✔ (Agoda 2026155830) · סוויטת Partial Ocean Pool King + ארוחת בוקר · באותו חוף — מעבר קצר מהטובקק." },
  "flight-kbv-usm": { n: "טיסה קראבי ← קוסמוי ✈️ PG266", en: "Krabi International Airport", city: "קראבי", cat: "transit",
    d: "01.10 · המראה 14:00 · Bangkok Airways, ישירה 50 דק' · מושבים 9A/9B · הזמנה FF7LFU (Booking.com)." },
  "ferry-samui-phangan": { n: "מעבורת לקופנגן ⛴", en: "Bangrak Pier Koh Samui", city: "קוסמוי", cat: "transit", approx: true,
    d: "מנמל בנגרק (Lomprayah / Seatran) ~30 דק'. כדאי לתאם דרך המלון הסעה+מעבורת מראש." },
  "hotel-panviman": { n: "Panviman Resort קופנגן", en: "Panviman Resort Koh Phangan", city: "קופנגן", cat: "hotel",
    d: "01–06.10 · הוזמן ✔ (Agoda 2041089608) · חדר Deluxe Jacuzzi Grande + ארוחת בוקר · מפרץ תונג נאי פאן נוי." },
  "ferry-phangan-samui": { n: "מעבורת חזרה לסמוי ⛴", en: "Thong Sala Pier Koh Phangan", city: "קופנגן", cat: "transit", approx: true,
    d: "06.10 · מנמל תונג סאלה ~30-45 דק' לסמוי." },
  "hotel-hansar": { n: "Hansar Samui Resort", en: "Hansar Samui Resort", city: "קוסמוי", cat: "hotel",
    d: "06–13.10 · הוזמן ✔ (Agoda 2026143615) · 5 כוכבים על חוף בופוט · Fisherman's Village במרחק הליכה · ארוחת בוקר לשניים." },
  "flight-usm-bkk": { n: "טיסה סמוי ← בנגקוק ✈️", en: "Samui International Airport", city: "קוסמוי", cat: "transit",
    d: "13.10 · טרם נסגר — לתאם מול טיסת ההמשך לישראל.", book: "להזמין כשיתבררו פרטי הטיסה הביתה" },
  "bkk-airport": { n: "בנגקוק ← ישראל ✈️", en: "Suvarnabhumi Airport Bangkok", city: "בנגקוק", cat: "transit",
    d: "כנראה אחרי 13.10 — התאריך המדויק לא מופיע בקבלות. לוודא בכרטיס האלקטרוני (הזמנה 63900)." },
});

DAYS.push(
  { id: "t1", n: 17, c: "TH", label: "קראבי · 26–28.09", short: "קראבי א׳", date: "26–28.09", dfrom: "26.09", dto: "27.09",
    city: "קראבי", color: "#0284c7", title: "נחיתה בקראבי — The Tubkaak",
    sum: "נחיתה מטוקיו וצ'ק-אין בטובקק. חוף, בריכה והתאוששות מהקצב של יפן. אטרקציות יתווספו בהמשך.",
    hotel: "hotel-tubkaak",
    transit: "משדה התעופה של קראבי ~40 דק' נסיעה למלון — לתאם הסעה מראש.",
    stops: ["arr-kbv", "hotel-tubkaak"] },
  { id: "t2", n: 18, c: "TH", label: "קראבי · 28.09–01.10", short: "קראבי ב׳", date: "28.09–01.10", dfrom: "28.09", dto: "30.09",
    city: "קראבי", color: "#0f766e", title: "Banyan Tree קראבי",
    sum: "מעבר לבניאן טרי — בריכה, ספא ושקיעות. רעיונות להמשך: שייט 4 איים, לגונת האמרלד, ריילי ביץ'.",
    hotel: "hotel-banyan",
    stops: ["hotel-banyan"] },
  { id: "t3", n: 19, c: "TH", label: "קופנגן · 01–06.10", short: "קופנגן", date: "01–06.10", dfrom: "01.10", dto: "05.10",
    city: "קופנגן", color: "#15803d", title: "Panviman קופנגן",
    sum: "טיסה קצרה לסמוי, מעבורת לקופנגן — 5 לילות בפנווימאן שמעל מפרץ תונג נאי פאן.",
    hotel: "hotel-panviman",
    transit: "PG266 בשעה 14:00 (50 דק') ← נמל בנגרק ← מעבורת לקופנגן.",
    stops: ["flight-kbv-usm", "ferry-samui-phangan", "hotel-panviman"] },
  { id: "t4", n: 20, c: "TH", label: "קוסמוי · 06–13.10", short: "קוסמוי", date: "06–13.10", dfrom: "06.10", dto: "12.10",
    city: "קוסמוי", color: "#b45309", title: "Hansar קוסמוי",
    sum: "שבוע בהאנסר על חוף בופוט — שווקי לילה, Fisherman's Village והמון בריכה.",
    hotel: "hotel-hansar",
    transit: "מעבורת קופנגן ← סמוי ~45 דק', ומשם נסיעה קצרה לבופוט.",
    stops: ["ferry-phangan-samui", "hotel-hansar"] },
  { id: "t5", n: 21, c: "TH", label: "בנגקוק · 13.10 ←", short: "בנגקוק", date: "13.10 והלאה", dfrom: "13.10", dto: "14.10",
    city: "בנגקוק", color: "#6d28d9", title: "בנגקוק — וטיסה הביתה",
    sum: "טיסה מסמוי לבנגקוק והמשך לישראל. תאריך הטיסה הביתה טרם ודאי — לבדוק בכרטיס.",
    hotel: null,
    stops: ["flight-usm-bkk", "bkk-airport"] }
);

/* מלונות — לתצוגת כרטיס היום */
const HOTELS = {
  "hotel-shiodome": { nights: "10–13.09 + 22–26.09", booked: true },
  "hotel-nohga":    { nights: "13–17.09", booked: true },
  "hotel-flag":     { nights: "17–21.09", booked: true },
  "hotel-suiun":    { nights: "21–22.09 (לילה אחד)", booked: true },
  "hotel-tubkaak":  { nights: "26–28.09 · 2 לילות", booked: true },
  "hotel-banyan":   { nights: "28.09–01.10 · 3 לילות", booked: true },
  "hotel-panviman": { nights: "01–06.10 · 5 לילות", booked: true },
  "hotel-hansar":   { nights: "06–13.10 · 7 לילות", booked: true },
};

/* =========================================================
   קטלוג החלפות — מסעדות ואטרקציות נוספות מהחוברת.
   ללא קואורדינטות מדויקות → ימוקמו אוטומטית בעת הוספה.
   ========================================================= */
const CITY_CENTERS = {
  "טוקיו":  [35.6762, 139.7503],
  "קיוטו":  [35.0116, 135.7681],
  "אוסקה":  [34.6937, 135.5023],
  "נארה":   [34.6851, 135.8048],
  "האקונה": [35.2324, 139.1069],
  "קראבי":  [8.0863, 98.9063],
  "קופנגן": [9.7500, 100.0140],
  "קוסמוי": [9.5120, 100.0136],
  "בנגקוק": [13.7563, 100.5018],
};

const CATALOG = [
  /* --- אטרקציות נוספות (Klook, קוד OMERINJAPAN) --- */
  { n: "מופע סומו", en: "Sumo Show Tokyo", city: "טוקיו", cat: "exp", klook: "https://shorturl.at/Y6Imk" , k: "attr", ll: [35.69727, 139.79324] , addr: "28, Yokoami, Sumida" },
  { n: "קרטינג ברחובות טוקיו", en: "Street Karting Tokyo", city: "טוקיו", cat: "exp", klook: "https://shorturl.at/ZVclF", note: "דרוש רישיון נהיגה בינלאומי!" , k: "bar" },
  { n: "פארק הארי פוטר (Warner Bros)", en: "Warner Bros Studio Tour Tokyo Harry Potter", city: "טוקיו", cat: "exp", klook: "https://shorturl.at/jgbe9" , k: "attr", ll: [35.74562, 139.64575] , addr: "リバーゲート, Kasugacho, Nerima" },
  { n: "Shibuya Sky — תצפית גגות", en: "Shibuya Sky", city: "טוקיו", cat: "site", klook: "https://shorturl.at/pg7D6" , k: "attr", ll: [35.65829, 139.70226] , addr: "B3F, Shibuya" },
  { n: "פארק סנריו (הלו קיטי)", en: "Sanrio Puroland", city: "טוקיו", cat: "exp", klook: "https://shorturl.at/dnKgP" , k: "attr" },
  { n: "מוזיאון-אקווריום בגינזה", en: "Art Aquarium Museum Ginza", city: "טוקיו", cat: "site", klook: "https://shorturl.at/4Ql4o" , k: "attr", ll: [35.67138, 139.76571] , addr: "16, Ginza, Chuo" },
  { n: "טוקיו דיסני-סי (ירד מהמסלול)", en: "Tokyo DisneySea", city: "טוקיו", cat: "exp", klook: "https://shorturl.at/BFd0u", note: "אם מתחשק להחזיר — יום שלם, שעה לפני פתיחה" , k: "attr", ll: [35.62765, 139.88865] , addr: "Maihama, Urayasu" },
  { n: "teamLab אוסקה", en: "teamLab Botanical Garden Osaka", city: "אוסקה", cat: "exp", klook: "https://shorturl.at/mDUBh" , k: "attr", ll: [34.61112, 135.52056] , addr: "Nagai-Kouen Avenue, Koenminamiyata 1-chome, Higashisumiyoshi Ward, Osaka" },
  { n: "סיור בעברית בטוקיו (סוזי)", en: "Tokyo", city: "טוקיו", cat: "exp", note: "קוד OMERINJAPAN — סיור עם סוזי, חיה ביפן 20+ שנה" , k: "attr" },
  { n: "סיור אוכל בעברית באוסקה (לירן)", en: "Osaka", city: "אוסקה", cat: "exp", note: "קבוצות קטנות עד 8 — אווירה, אלכוהול והיסטוריה" , k: "attr" },

  /* --- טוקיו: מסעדות --- */
  { n: "Kanazawa Maimon Sushi", en: "Kanazawa Maimon Sushi Tokyo", city: "טוקיו", cat: "food", note: "סושי מסוע — רשת איכותית" , k: "sushi", ll: [35.70685, 139.77333] , addr: "Ueno, Taito" },
  { n: "Nemuro Hanamaru Ginza", en: "Kaitenzushi Nemuro Hanamaru Ginza", city: "טוקיו", cat: "food", note: "סושי מסוע איכותי" , k: "sushi", ll: [35.67177, 139.76219] , addr: "1, Ginza, Chuo" },
  { n: "Sushi Kenshin (אביסו)", en: "Sushi Kenshin Ebisu", city: "טוקיו", cat: "food", note: "אומקסה, אפשרי ללא פירות ים — להזמין מראש", book: true , k: "other" },
  { n: "Jikasei MENSHO", en: "Jikasei Mensho Shibuya", city: "טוקיו", cat: "food", note: "ראמן בשיבויה" , k: "ramen", ll: [35.66200, 139.69889] , addr: "1, Udagawachō, Shibuya" },
  { n: "Ramen Break Beats", en: "Ramen Break Beats Meguro", city: "טוקיו", cat: "food", note: "ראמן" , k: "ramen", ll: [35.63353, 139.69876] , addr: "Aburadzura-dori, Meguro" },
  { n: "Afuri", en: "Afuri Ramen Ebisu", city: "טוקיו", cat: "food", note: "ראמן יוזו — רשת מומלצת 🌱" , k: "ramen" },
  { n: "Bills Ginza", en: "Bills Ginza", city: "טוקיו", cat: "food", note: "ארוחת בוקר" , k: "cafe", ll: [35.67328, 139.76658] , addr: "Ginza Gasutou-dori Street, Ginza, Chuo" },
  { n: "Blue Bottle Coffee", en: "Blue Bottle Coffee Tokyo", city: "טוקיו", cat: "food", note: "רשת קפה" , k: "cafe", ll: [35.68893, 139.70209] , addr: "6, Shinjuku" },
  { n: "A Happy Pancake", en: "A Happy Pancake Omotesando", city: "טוקיו", cat: "food", note: "פנקייק פלאפי" , k: "cafe" },
  { n: "Flipper's שיבויה", en: "Flippers Shibuya", city: "טוקיו", cat: "food", note: "פנקייק פלאפי" , k: "cafe" },
  { n: "Micasadeco & Cafe", en: "Micasadeco Cafe Jingumae", city: "טוקיו", cat: "food", note: "פנקייק פלאפי" , k: "cafe", ll: [35.66541, 139.70390] , addr: "Cat Street, Jingumae, Shibuya" },
  { n: "BAM BI COFFEE", en: "Bam Bi Coffee Tokyo", city: "טוקיו", cat: "food", note: "פנקייק + קפה מעולה" , k: "cafe" },
  { n: "Verve Coffee Roasters", en: "Verve Coffee Roasters Shinjuku", city: "טוקיו", cat: "food", note: "בית קפה" , k: "cafe", ll: [35.68841, 139.70146] , addr: "55, Sendagaya, Shibuya" },
  { n: "Nikuya no Daidokoro", en: "Nikuya no Daidokoro Shinjuku", city: "טוקיו", cat: "food", note: "יאקיניקו" , k: "meat" },
  { n: "Han no Daidokoro Bettei", en: "Han no Daidokoro Bettei Shibuya", city: "טוקיו", cat: "food", note: "יאקיניקו" , k: "meat", ll: [35.65970, 139.69781] , addr: "道玄坂小路, Dōgenzaka, Shibuya" },
  { n: "WAGYU NIKUTARASHI", en: "Wagyu Yakiniku Nikutarashi Tokyo", city: "טוקיו", cat: "food", note: "יאקיניקו" , k: "meat" },
  { n: "Jambo Hanare", en: "Jambo Hanare Tokyo", city: "טוקיו", cat: "food", note: "יאקיניקו" , k: "meat" },
  { n: "GINZA STEAK", en: "Ginza Steak Chuo", city: "טוקיו", cat: "food", note: "טפניאקי" , k: "meat" },
  { n: "Teppanyaki Akasaka", en: "Teppanyaki Akasaka Tokyo", city: "טוקיו", cat: "food", note: "טפניאקי" , k: "meat" },
  { n: "NOBU Tokyo", en: "Nobu Tokyo", city: "טוקיו", cat: "food", note: "מערבית-יפנית — להזמין מראש", book: true , k: "fine", ll: [35.66632, 139.74378] , addr: "Edomisaka, Toranomon, Minato" },
  { n: "PST Roppongi", en: "Pizza Studio Tamaki Roppongi", city: "טוקיו", cat: "food", note: "פיצה" , k: "italian" },
  { n: "pizza marumo", en: "Pizza Marumo Ebisu", city: "טוקיו", cat: "food", note: "פיצה" , k: "italian", ll: [35.64529, 139.70851] , addr: "Meguro Mita Street, Ebisu-Minami, Shibuya" },
  { n: "Tír na nÓg", en: "Tir na nOg Bar Tokyo", city: "טוקיו", cat: "exp", note: "בר קוקטיילים" , k: "bar" },
  { n: "Bar TRENCH", en: "Bar Trench Ebisu", city: "טוקיו", cat: "exp", note: "בר קוקטיילים" , k: "bar", ll: [35.64842, 139.70792] , addr: "Ebisu 1st Street, Ebisu-Nishi, Shibuya" },
  { n: "THE MUSIC BAR CAVE", en: "The Music Bar Cave Shibuya", city: "טוקיו", cat: "exp", note: "בר רטרו" , k: "bar" },
  { n: "A10 (בר סודי)", en: "A10 Bar Shibuya", city: "טוקיו", cat: "exp", note: "בר קוקטיילים סודי" , k: "bar" },
  { n: "Crony (מישלן)", en: "Crony Nishiazabu", city: "טוקיו", cat: "food", note: "צרפתית מישלן — להזמין מראש", book: true , k: "fine", mich: true },
  { n: "SÉZANNE (מישלן)", en: "Sezanne Tokyo", city: "טוקיו", cat: "food", note: "צרפתית מישלן — להזמין מראש", book: true , k: "fine", mich: true },
  { n: "MAZ (מישלן)", en: "MAZ Tokyo", city: "טוקיו", cat: "food", note: "פרואנית מישלן — להזמין מראש", book: true , k: "fine", mich: true },
  { n: "Kabi (מישלן)", en: "Kabi Meguro", city: "טוקיו", cat: "food", note: "יפנית מודרנית — להזמין מראש", book: true , k: "fine", mich: true },

  /* --- קיוטו: מסעדות --- */
  { n: "Sushi Ishimatsu", en: "Sushi Ishimatsu Kyoto", city: "קיוטו", cat: "food", note: "סושי" , k: "sushi" },
  { n: "MoriMori Sushi", en: "Morimori Sushi Shijo Kawaramachi", city: "קיוטו", cat: "food", note: "סושי מסוע" , k: "sushi", ll: [35.00341, 135.76967] , addr: "Kawaramachi Street, Junpucho, Shimogyo Ward, Kyoto" },
  { n: "Sushi Kizaemon", en: "Sushi Kizaemon Kyoto", city: "קיוטו", cat: "food", note: "סושי" , k: "sushi" },
  { n: "Maruman", en: "Maruman Sushi Kyoto", city: "קיוטו", cat: "food", note: "סושי" , k: "sushi" },
  { n: "KYOTO ENGINE RAMEN", en: "Kyoto Engine Ramen", city: "קיוטו", cat: "food", note: "ראמן — אופציות צמחוניות 🌱" , k: "ramen" },
  { n: "Sugari", en: "Sugari Ramen Kyoto", city: "קיוטו", cat: "food", note: "ראמן" , k: "ramen" },
  { n: "Vegan Ramen UZU", en: "Vegan Ramen Uzu Kyoto", city: "קיוטו", cat: "food", note: "ראמן טבעוני 🌱" , k: "ramen", ll: [35.01467, 135.76804] , addr: "新烏丸通, Gyoganjimonzencho, Nakagyo Ward, Kyoto" },
  { n: "Sabanji", en: "Sabanji Ramen Kyoto", city: "קיוטו", cat: "food", note: "ראמן בשרי" , k: "ramen" },
  { n: "Panel Cafe", en: "Panel Cafe Kyoto", city: "קיוטו", cat: "food", note: "פנקייק פלאפי" , k: "cafe" },
  { n: "Maccha House", en: "Maccha House Kyoto", city: "קיוטו", cat: "food", note: "מאצ'ה" , k: "cafe", ll: [35.00449, 135.76948] , addr: "Kawaramachi Street, Komeyacho, Nakagyo Ward, Kyoto" },
  { n: ".common", en: "common cafe Kyoto", city: "קיוטו", cat: "food", note: "בית קפה" , k: "cafe" },
  { n: "Blue Bottle קיוטו", en: "Blue Bottle Coffee Kyoto", city: "קיוטו", cat: "food", note: "רשת קפה" , k: "cafe", ll: [35.01139, 135.78949] , addr: "64, Nanzenji-Kusagawacho, Sakyō Ward, Kyoto" },
  { n: "ACTUAL KYOTO", en: "Actual Kyoto cafe", city: "קיוטו", cat: "food", note: "בית קפה" , k: "cafe" },
  { n: "Gyūrakutei", en: "Yakiniku Gyurakutei Kyoto", city: "קיוטו", cat: "food", note: "יאקיניקו" , k: "meat", ll: [35.00385, 135.75677] , addr: "Shinmachi Street, Mikagecho, Shimogyo Ward, Kyoto" },
  { n: "Hikiniku to Kome", en: "Hikiniku to Come Kyoto", city: "קיוטו", cat: "food", note: "קציצות וואגיו ואורז" , k: "meat", ll: [35.00510, 135.77454] , addr: "末吉町通, Kiyomotocho, Higashiyama Ward, Kyoto" },
  { n: "Burger Revolution", en: "Burger Revolution Kyoto", city: "קיוטו", cat: "food", note: "המבורגר וואגיו" , k: "meat" },
  { n: "Itoh Dining", en: "Itoh Dining Kyoto Gion", city: "קיוטו", cat: "food", note: "סטייקים — יוקרתית" , k: "meat", ll: [35.00518, 135.77399] , addr: "80, 末吉町通, Sueyoshicho, Higashiyama Ward" },
  { n: "MOTOI Gyoza", en: "Motoi Gyoza Kyoto", city: "קיוטו", cat: "food", note: "גיוזה מישלן" , k: "jp", mich: true },
  { n: "koisus — קארי וטמפורה", en: "Curry Tempura Koisus Kyoto", city: "קיוטו", cat: "food", note: "קארי וטמפורה" , k: "jp", ll: [35.00026, 135.77116] , addr: "Kawabata Street, Sujakucho, Higashiyama Ward, Kyoto" },
  { n: "Pizzeria Marita", en: "Pizzeria Marita Kyoto", city: "קיוטו", cat: "food", note: "פיצה" , k: "italian" },
  { n: "Bigoli", en: "Bigoli Kyoto", city: "קיוטו", cat: "food", note: "פסטה" , k: "italian", ll: [35.00443, 135.76080] , addr: "Higashinotōin Street, Misayamacho, Nakagyo Ward, Kyoto" },
  { n: "Chao Chao Gyoza", en: "Chao Chao Gyoza Shijo Kawaramachi", city: "קיוטו", cat: "food", note: "גיוזה" , k: "jp", ll: [35.00284, 135.76952] , addr: "Kawaramachi Street, Matsukawacho, Shimogyo Ward, Kyoto" },
  { n: "music bar Beatle momo", en: "Music Bar Beatle Momo Kyoto", city: "קיוטו", cat: "exp", note: "בר רטרו" , k: "bar" },
  { n: "Masuya Saketen", en: "Masuya Saketen Kyoto", city: "קיוטו", cat: "exp", note: "בר סאקה" , k: "bar", ll: [35.00418, 135.76641] , addr: "Gokomachi Street, Dainichicho, Nakagyo Ward, Kyoto" },
  { n: "mixology bar Smooth", en: "Mixology Bar Smooth Kyoto", city: "קיוטו", cat: "exp", note: "בר קוקטיילים" , k: "bar" },
  { n: "Hyotei (3 כוכבי מישלן)", en: "Hyotei Kyoto", city: "קיוטו", cat: "food", note: "קייסקי ~450 שנה — להזמין מראש", book: true , k: "fine", mich: true, ll: [35.01142, 135.78673] , addr: "Niō Gate Street, Nanzenji-Kusagawacho, Sakyō Ward, Kyoto" },
  { n: "Tenjaku (מישלן)", en: "Tenjaku Tempura Kyoto", city: "קיוטו", cat: "food", note: "טמפורה עונתית — להזמין מראש", book: true , k: "jp", mich: true },
  { n: "Kikunoi Honten (3 כוכבים)", en: "Kikunoi Honten Kyoto", city: "קיוטו", cat: "food", note: "קייסקי — להזמין מראש", book: true , k: "fine", mich: true },
  { n: "Kōdaiji Jūgyūan (2 כוכבים)", en: "Kodaiji Jugyuan Kyoto", city: "קיוטו", cat: "food", note: "קייסקי — להזמין מראש", book: true , k: "fine", mich: true, ll: [35.00030, 135.78060] , addr: "Daidokoro Slope, Shimogawara-chō, Higashiyama Ward, Kyoto" },

  /* --- אוסקה: מסעדות --- */
  { n: "Sushi Sakaba Sashisu", en: "Sushi Sakaba Sashisu Osaka", city: "אוסקה", cat: "food", note: "סושי" , k: "sushi" },
  { n: "Daiki-suisan דוטונבורי", en: "Daiki Suisan Kaitenzushi Dotonbori", city: "אוסקה", cat: "food", note: "סושי מסוע" , k: "sushi", ll: [34.66853, 135.50291] , addr: "24, Dotonbori 1, Chūō Ward, Osaka" },
  { n: "Sushi Hayata", en: "Sushi Hayata Osaka", city: "אוסקה", cat: "food", note: "סושי" , k: "sushi" },
  { n: "Sanshin — אומקסה", en: "Sushi Sanshin Osaka", city: "אוסקה", cat: "food", note: "אומקסה — להזמין מראש", book: true , k: "other" },
  { n: "Ichiran נמבה", en: "Ichiran Namba Midosuji", city: "אוסקה", cat: "food", note: "ראמן — ללא חזיר" , k: "ramen" },
  { n: "OSAKA ENGINE RAMEN", en: "Osaka Engine Ramen", city: "אוסקה", cat: "food", note: "ראמן" , k: "ramen" },
  { n: "Kyushu Ramen Kio", en: "Kyushu Ramen Kio Dotonbori", city: "אוסקה", cat: "food", note: "ראמן אותנטי" , k: "ramen", ll: [34.66458, 135.50362] , addr: "Sennichimae Doguyasuji Shopping St, Nanba-Sennichimae, Chūō Ward, Osaka" },
  { n: "Mugito Mensuke", en: "Mugito Mensuke Osaka", city: "אוסקה", cat: "food", note: "ראמן מומלץ מישלן" , k: "ramen", mich: true },
  { n: "Ourlog coffee", en: "Ourlog Coffee Osaka", city: "אוסקה", cat: "food", note: "קפה ומאפה" , k: "cafe", ll: [34.66074, 135.53601] , addr: "御幸通商店街, Momodani 3-chome, Ikuno Ward, Osaka" },
  { n: "Brooklyn Roasting Co.", en: "Brooklyn Roasting Company Kitahama", city: "אוסקה", cat: "food", note: "קפה ומאפה" , k: "cafe", ll: [34.69101, 135.50919] , addr: "Tosabori Street, Kitahama 1-chome, Chūō Ward, Osaka" },
  { n: "GLITCH COFFEE", en: "Glitch Coffee Osaka", city: "אוסקה", cat: "food", note: "קפה ספשלטי" , k: "cafe", ll: [34.69366, 135.49553] , addr: "4, Nakanoshima 3-chome, Kita Ward, Osaka" },
  { n: "CAFE TALES", en: "Cafe Tales Osaka", city: "אוסקה", cat: "food", note: "ארוחת בוקר" , k: "cafe", ll: [34.68103, 135.50364] , addr: "Sankyubashi-suji, Kyutaromachi 2-chome, Chūō Ward, Osaka" },
  { n: "Wagyu Teppanyaki OUSAKA", en: "Wagyu Teppanyaki Ousaka", city: "אוסקה", cat: "food", note: "טפניאקי יוקרתי — להזמין מראש", book: true , k: "meat" },
  { n: "Matsusakagyu M Hanare", en: "Matsusakagyu Yakiniku M Hanare Namba", city: "אוסקה", cat: "food", note: "יאקיניקו" , k: "meat" },
  { n: "KITAN HIBIKI", en: "Kitan Hibiki Yakiniku Steak Osaka", city: "אוסקה", cat: "food", note: "וואגיו / סטייק" , k: "meat" },
  { n: "La Pizza Regalo", en: "La Pizza Napoletana Regalo Osaka", city: "אוסקה", cat: "food", note: "איטלקית" , k: "italian" },
  { n: "Tempura Makino", en: "Tempura Makino Namba", city: "אוסקה", cat: "food", note: "טמפורה" , k: "jp", ll: [34.70607, 135.51122] , addr: "18, Tenjinbashi 4-chome, Kita Ward, Osaka" },
  { n: "Yakitori Ichimatsu", en: "Yakitori Ichimatsu Osaka", city: "אוסקה", cat: "food", note: "יאקיטורי מומלץ מישלן" , k: "meat", mich: true },
  { n: "Alto Tritone", en: "Alto Tritone Osaka", city: "אוסקה", cat: "food", note: "איטלקית קטנה" , k: "italian" },
  { n: "Osteria La Cicerchia", en: "Osteria La Cicerchia Osaka", city: "אוסקה", cat: "food", note: "איטלקית מומלצת מישלן" , k: "italian", mich: true },
  { n: "BAR Inc", en: "Bar Inc Osaka", city: "אוסקה", cat: "exp", note: "בר קוקטיילים" , k: "bar" },
  { n: "Bar Nayuta", en: "Bar Nayuta Osaka", city: "אוסקה", cat: "exp", note: "בר קוקטיילים" , k: "bar", ll: [34.67204, 135.49835] , addr: "大黒橋筋, Nishi-Shinsaibashi 1-chome, Chūō Ward, Osaka" },
  { n: "Bar N", en: "Bar N Osaka", city: "אוסקה", cat: "exp", note: "בר משפחתי" , k: "bar" },
  { n: "Akashic Records", en: "Osaka Cocktail Library Akashic Records", city: "אוסקה", cat: "exp", note: "בר קוקטיילים" , k: "bar" },
  { n: "La Cime (2 כוכבים)", en: "La Cime Osaka", city: "אוסקה", cat: "food", note: "צרפתית-יפנית — להזמין מראש", book: true , k: "fine", mich: true },
  { n: "HAJIME (3 כוכבים)", en: "Hajime Osaka", city: "אוסקה", cat: "food", note: "גסטרונומיה — להזמין מראש", book: true , k: "fine", mich: true },
  { n: "Koryu (2 כוכבים)", en: "Koryu Osaka", city: "אוסקה", cat: "food", note: "קייסקי — להזמין מראש", book: true , k: "fine", mich: true },
  { n: "Tenjimbashi Aoki (2 כוכבים)", en: "Tenjimbashi Aoki Osaka", city: "אוסקה", cat: "food", note: "קייסקי — מקומות מוגבלים", book: true , k: "fine", mich: true },
];

/* משימות שליחת מזוודות (Takkyubin) — לפי החוברת: למסור לפחות 24ש' לפני צ'ק-אאוט */
const LUGGAGE = [
  { id: "lug-1", day: "d2", title: "🧳 למסור מזוודות לקיוטו",
    d: "בבוקר, בקבלה, עם אישור ההזמנה של Nohga Kiyomizu — המזוודות ייסעו ישירות לקיוטו ויחכו לכם שם. משאירים תיק יום לשינקנסן." },
  { id: "lug-2", day: "d6", title: "🧳 למסור מזוודות לאוסקה",
    d: "בבוקר, בקבלה, עם אישור ההזמנה של HOTEL THE FLAG שינסאיבאשי. לשמור עותק של טפסי המשלוח." },
  { id: "lug-3", day: "d10", title: "🧳 חשוב! מזוודות ישר לטוקיו — מדלגות על האקונה",
    d: "למסור בקבלה באוסקה עם אישור Royal Park Iconic שיודומה. להאקונה לוקחים רק תיק לילה קטן לריוקאן — ככה נוסעים קל ברכבל ובשייט." },
];

/* טיפים כלליים — פאנל מידע */
const TIPS = [
  { t: "הזמנות", d: "אטרקציות — חודש מראש (Klook, קוד OMERINJAPAN חוץ מדיסני/יוניברסל). שינקנסן — 1-2 שבועות. מסעדות — דרך קבלת המלון או OMAKASE.IN / TableCheck / Tabelog." },
  { t: "תחבורה", d: "Google Maps לניווט. כרטיס SUICA דיגיטלי באייפון — רכבות, אוטובוסים וגם קניות. מוניות: אפליקציית GO או Uber." },
  { t: "מזוודות", d: "שליחת מזוודות בין מלונות עובדת מצוין — למסור בקבלה 24 שעות לפני צ'ק-אאוט עם אישור המלון הבא. קריטי ליום האקונה!" },
  { t: "כסף", d: "מזומן להמיר בארץ (לא בשדה ביפן). כספומטים: 7-Eleven. Tax-Free מ-¥5,000 עם דרכון פיזי. BIC Camera: עוד 5% הנחה באשראי." },
  { t: "eSIM", d: "VOYE Global — קוד OMERINJAPAN ל-15% הנחה. להתקין לפני הטיסה. voyeglobal.com" },
  { t: "מעומר", d: "אל תיפלו לפומו — אי אפשר להספיק הכול, וזה בסדר. תטיילו בקצב שלכם ותיהנו!" },
];

/* שמות וכתובות ביפנית — לכרטיסי 'הראה לנהג מונית' 🚕 */
const JA = {
  "airport-dep": { n: "羽田空港", a: "" },
  "akihabara": { n: "秋葉原電気街", a: "千代田区外神田9" },
  "arabica-arashiyama": { n: "アラビカ京都 嵐山", a: "京都府京都市右京区嵯峨中ノ島町二条停車場嵐山線" },
  "bamboo-grove": { n: "嵐山 竹林の小径", a: "京都府京都市右京区嵯峨小倉山田淵山町竹林の道" },
  "dotonbori": { n: "道頓堀", a: "大阪府大阪市中央区道頓堀一丁目戎橋筋商店街" },
  "fushimi-castle": { n: "伏見桃山城", a: "京都府京都市伏見区深草大亀谷五郎太町上板橋通" },
  "fushimi-inari": { n: "伏見稲荷大社", a: "京都府京都市伏見区深草稲荷御前町表参道" },
  "gekkeikan": { n: "月桂冠大倉記念館", a: "京都府京都市伏見区東柳町" },
  "ginza-ramen": { n: "銀座 篝(かがり)本店", a: "" },
  "ginza-sand": { n: "銀座サンド", a: "中央区銀座交詢社通り" },
  "godzilla": { n: "ホテルグレイスリー新宿 ゴジラヘッド", a: "新宿区歌舞伎町1" },
  "gora-park": { n: "箱根強羅公園", a: "神奈川県箱根町木賀" },
  "hachiko": { n: "渋谷 ハチ公前", a: "渋谷区道玄坂神宮通り" },
  "hakkoku": { n: "はっこく 銀座", a: "" },
  "hakone-shrine": { n: "箱根神社", a: "神奈川県箱根町神社通り" },
  "hotel-flag": { n: "ホテル・ザ・フラッグ 心斎橋", a: "大阪府大阪市中央区東心斎橋一丁目30" },
  "hotel-nohga": { n: "ノーガホテル 清水 京都", a: "京都府京都市東山区五条橋東四丁目五条通" },
  "hotel-shiodome": { n: "ザ ロイヤルパークホテル アイコニック 東京汐留", a: "港区東新橋新虎自転車道" },
  "hotel-suiun": { n: "箱根 翠雲(すいうん)", a: "" },
  "isuien": { n: "依水園", a: "奈良県奈良市春日野町東大寺参道" },
  "kabukicho-goldengai": { n: "歌舞伎町・ゴールデン街", a: "新宿区歌舞伎町" },
  "kaiyukan": { n: "海遊館", a: "大阪府大阪市港区海岸通一丁目一条通" },
  "kamaiki": { n: "釜粋", a: "奈良県奈良市川之上突抜町東向商店街" },
  "kappabashi": { n: "かっぱ橋道具街", a: "台東区松が谷" },
  "kasuga-taisha": { n: "春日大社", a: "奈良県奈良市春日野町" },
  "katsugyu-dogenzaka": { n: "牛カツ 京都勝牛 渋谷道玄坂", a: "" },
  "kijurou": { n: "嵐山 喜重郎", a: "京都府京都市右京区嵯峨天龍寺立石町宇多野嵐山山田線" },
  "kinkakuji": { n: "金閣寺", a: "京都府京都市北区金閣寺町" },
  "kiyomizudera": { n: "清水寺", a: "京都府京都市東山区清水一丁目常盤橋" },
  "kyoto-gyoen": { n: "京都御苑", a: "京都府京都市上京区京都御苑3" },
  "kyoto-station": { n: "京都駅", a: "京都府京都市下京区東塩小路町901" },
  "meiji-shrine": { n: "明治神宮", a: "渋谷区代々木神園町1" },
  "midtown-2121": { n: "21_21 DESIGN SIGHT", a: "港区赤坂4" },
  "mitsukoshi-ginza": { n: "銀座三越", a: "中央区銀座晴海通り" },
  "monkey-park": { n: "嵐山モンキーパーク", a: "京都府京都市西京区嵐山中尾下町宇多野嵐山山田線" },
  "nakamise": { n: "仲見世通り", a: "台東区浅草6" },
  "nakatanidou": { n: "中谷堂", a: "奈良県奈良市川之上突抜町三条通り1" },
  "namba-yasaka": { n: "難波八阪神社", a: "大阪府大阪市浪速区元町二丁目大国町筋" },
  "nara-park": { n: "奈良公園", a: "奈良県奈良市春日野町東大寺参道" },
  "nijo-castle": { n: "二条城", a: "京都府京都市中京区二条城町東橋" },
  "nishiki-market": { n: "錦市場", a: "京都府京都市中京区東魚屋町錦小路通" },
  "nissan-ginzasix": { n: "GINZA SIX", a: "中央区銀座みゆき通り" },
  "odawara-station": { n: "小田原駅", a: "神奈川県小田原市城山一丁目小田原停車場線" },
  "ogawa-lab": { n: "小川珈琲ラボラトリー 下北沢", a: "世田谷区北沢区道（線路地下化上部跡地）" },
  "omotesando": { n: "表参道", a: "港区北青山青山通り" },
  "onodera-kyoto": { n: "回転寿司 銀座おのでら 京都", a: "" },
  "openair-museum": { n: "彫刻の森美術館", a: "神奈川県箱根町二ノ平" },
  "osaka-castle": { n: "大阪城", a: "大阪府大阪市中央区大阪城極楽橋" },
  "osaka-station": { n: "新大阪駅", a: "大阪府大阪市淀川区宮原一丁目新大阪地下道1" },
  "owakudani": { n: "大涌谷", a: "神奈川県箱根町大湧谷小湧谷線" },
  "pontocho": { n: "先斗町", a: "京都府京都市中京区中島町三条通" },
  "reload": { n: "reload 下北沢", a: "世田谷区北沢一番街本通り" },
  "rikuros": { n: "りくろーおじさんの店 なんば本店", a: "" },
  "roppongi-hills": { n: "六本木ヒルズ", a: "港区六本木1" },
  "sannenzaka": { n: "三年坂(産寧坂)", a: "京都府京都市東山区清水三丁目三年坂" },
  "savoy": { n: "サヴォイ 麻布十番", a: "港区麻布十番13" },
  "sbux-tsutaya": { n: "スターバックス SHIBUYA TSUTAYA店", a: "渋谷区神南神宮通り" },
  "sensoji": { n: "浅草寺", a: "台東区浅草1" },
  "setsugetsuka": { n: "銀座 雪月花", a: "" },
  "shibuya-parco": { n: "渋谷PARCO", a: "渋谷区宇田川町1" },
  "shijo-dori": { n: "四条通", a: "京都府京都市下京区御旅宮本町四条通B1" },
  "shinjuku-gyoen": { n: "新宿御苑", a: "新宿区内藤町" },
  "shinsaibashi": { n: "心斎橋筋商店街", a: "大阪府大阪市中央区宗右衛門町心斎橋筋1-6-4" },
  "skytree": { n: "東京スカイツリー", a: "墨田区押上2" },
  "takeshita-st": { n: "竹下通り", a: "渋谷区神宮前竹下通り" },
  "teamlab-biovortex": { n: "チームラボ バイオヴォルテックス 京都", a: "京都府京都市下京区東之町八条通" },
  "teamlab-borderless": { n: "チームラボボーダレス(麻布台ヒルズ)", a: "港区虎ノ門八幡通り" },
  "teamlab-planets": { n: "チームラボプラネッツ TOKYO 豊洲", a: "江東区豊洲16" },
  "todaiji": { n: "東大寺", a: "奈良県奈良市雑司町" },
  "togendai": { n: "桃源台港", a: "神奈川県箱根町仙石原湯河原箱根仙石原線" },
  "togetsukyo": { n: "渡月橋", a: "京都府京都市右京区嵯峨中ノ島町宇多野嵐山山田線" },
  "tokyo-station": { n: "東京駅", a: "千代田区丸の内エレベーター;2階" },
  "tokyo-tower": { n: "東京タワー", a: "港区芝公園8" },
  "tsukiji": { n: "築地場外市場", a: "中央区築地築地中通" },
  "ueno-park": { n: "上野公園", a: "台東区上野公園パンダ橋" },
  "umeda-sky": { n: "梅田スカイビル 空中庭園", a: "大阪府大阪市北区大淀中一丁目大阪伊丹線" },
  "uniqlo-ginza": { n: "ユニクロ 銀座店", a: "中央区銀座並木通り" },
  "uniqlo-shinjuku": { n: "ユニクロ 新宿本店", a: "" },
  "usj": { n: "ユニバーサル・スタジオ・ジャパン", a: "大阪府大阪市此花区桜島二丁目Amity Avenue2-1-33" },
  "yodobashi-umeda": { n: "ヨドバシカメラ マルチメディア梅田", a: "大阪府大阪市北区大深町" },
};

/* הטיסות — לתצוגה בפאנל המידע */
const FLIGHTS = [
  { r: "תל אביב ← טוקיו", d: "09.09 בלילה · נחיתה 10.09 בערב", note: "הזמנה 63900 · סוכן: עמר חן (ברון טורס) · לוודא שעות בכרטיס האלקטרוני" },
  { r: "טוקיו ← קראבי", d: "26.09", note: "קבלה 1357764 · bookaflight.co.il" },
  { r: "קראבי ← קוסמוי", d: "01.10 · המראה 14:00 · PG266", note: "Bangkok Airways · ישירה 50 דק' · מושבים 9A/9B · הזמנה FF7LFU" },
  { r: "קוסמוי ← בנגקוק", d: "13.10 — טרם הוזמן", note: "לסגור מול טיסת ההמשך" },
  { r: "בנגקוק ← תל אביב", d: "אחרי 13.10 — לוודא בכרטיס", note: "כלול בהזמנה 63900" },
];

/* קישורים מהירים */
const QUICKLINKS = [
  { t: "📶 VOYE eSIM — קוד OMERINJAPAN (-15%)", u: "https://voyeglobal.com" },
  { t: "🎟️ Klook — אטרקציות ושינקנסן", u: "https://www.klook.com" },
  { t: "🈂️ Google Translate", u: "https://translate.google.com" },
  { t: "🚕 GO Taxi (יפן)", u: "https://go.goinc.jp/" },
  { t: "🛵 Grab (תאילנד)", u: "https://www.grab.com" },
  { t: "🏨 Booking — הזמנות יפן", u: "https://www.booking.com" },
  { t: "🏝️ Agoda — הזמנות תאילנד", u: "https://www.agoda.com" },
  { t: "🍣 OMAKASE.IN — מסעדות יוקרה", u: "https://omakase.in" },
  { t: "🍜 TableCheck — הזמנת מסעדות", u: "https://www.tablecheck.com" },
];

/* חירום — לוודא מספרים לפני היציאה */
const EMERGENCY = [
  { t: "🇯🇵 יפן", items: ["משטרה: 110", "אמבולנס / כיבוי: 119", "קו תיירים JNTO באנגלית 24/7: 050-3816-2787", "שגרירות ישראל בטוקיו: +81-3-3264-0911"] },
  { t: "🇹🇭 תאילנד", items: ["משטרה: 191", "משטרת תיירות (אנגלית): 1155", "אמבולנס: 1669", "שגרירות ישראל בבנגקוק: +66-2-204-9200"] },
];
